version: '3.8'

services:
  autossh-tls:
    build: .
    environment:
      - SSH_HOST=tunnel.example.com
      - SSH_PORT=2222
      - SNI_HOST=tunnel.example.com
      - SSH_USER=tunnel
      - SSH_KEY_FILE=/root/.ssh/id_rsa
      - REMOTE_PORT=3306
    volumes:
      - ssh-config:/root/.ssh
    restart: unless-stopped

volumes:
  ssh-config:

