services:
  autossh-tls:
    image: nopenix/autossh-tls:latest
    environment:
      - SSH_HOST=c.example.com
      - SSH_PORT=443
      - SNI_HOST=tunnel-mysql.example.com
      - SSH_USER=tunnel
      - SSH_KEY_FILE=/root/.ssh/id_rsa
      - REMOTE_BIND_PORT=3306
      - TARGET_HOST=mysql
      - TARGET_PORT=3306
    volumes:
      - ./ssh:/root/.ssh:ro
    restart: unless-stopped